### ISSUE TITLE
Terraform 0.12: allow setting aws_launch_template.credit_specification.cpu_credits

### ISSUE THREAD

**Issue by asmgf** [traveloka/terraform-aws-autoscaling#27]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### New or Affected Resource(s)

* aws_launch_template

### Potential Terraform Configuration Changes

```hcl
provider "aws" {
  region = "ap-southeast-1"
}

module "asg" {
  source = "../.."

  service_name   = "fprbe"
  environment    = "production"
  product_domain = "fpr"
  description    = "Instances of fprbe-app"
  application    = "java-8"

  security_groups  = []
  instance_profile = "myinstance-profile"

  cpu_credits = "standard"

  image_owners = ["123456789012"]

  image_filters = [
    # See https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html for complete filter options
    {
      name   = "name"
      values = ["traveloka-fprbe-app-*"]
    },
    # If you want to directly specify the image ID
    {
      name   = "image-id"
      values = ["ami-91920591023019"]
    },
  ]

  launch_template_overrides = [
    {
      "instance_type" = "m5.large"
    },
    {
      "instance_type" = "m4.large"
    },
  ]

  user_data = "echo starting fprbe"
  key_name  = ""

  asg_vpc_zone_identifier  = ["subnet-a2b50c9d", "subnet-718c9efe"]
  asg_lb_target_group_arns = []

  asg_wait_for_capacity_timeout = "1m"
}

```

**Comment by salvianreynaldi** [comment]
as #28 is closed, kindly check if this issue still persists, @asmgf

**Comment by asmgf** [comment]
As I shared in the pull request it doesn't seem to work. Even with workaround there seem to be some limitation from AWS: https://github.com/traveloka/terraform-aws-autoscaling/pull/28#issuecomment-519344215
