### ISSUE TITLE
Add toggle for public_ip_association

### ISSUE THREAD

**Issue by franzramadhan** [traveloka/terraform-aws-autoscaling#33]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### New or Affected Resource(s)

* `resource "aws_launch_template" "main" {}`

### Potential Terraform Configuration Changes

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.

network_interfaces {
    associate_public_ip_address = "${var.associate_public_ip}"
}

variable "associate_public_ip" {
  description = "Whether to associate public IP to the instance"
  default     = "false"
}
```

### References

* https://www.terraform.io/docs/providers/aws/r/launch_template.html#associate_public_ip_address

**Comment by sumodirjo** [comment]
Hi @franzramadhan ,
My understanding this feature is to associate non Elastic IP to instance. Do you mind potential use case by adding this feature to our autoscaling module?
